name: ssi-sdk-ci

# when:
#   - a pull request is opened against main
#   - commits are pushed to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs "at  2pm every day"
    - cron: '0 14 * * *'
  # used to run action manually via the UI
  workflow_dispatch:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      - name: Install Mage
        run: go install github.com/magefile/mage

      - name: Check Vulnerabilities
        run: mage -v vuln
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      - name: Install Mage
        run: go install github.com/magefile/mage

      - name: Build
        run: mage build

      - name: Test
        run: mage citest
      
      - name: Fuzz tests
        run: mage fuzz

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3